# Environment name
env: 'local'
hostname: 'gelato-technical-challenge.local'

# Number of replicas to spin up for deployment
replicas: 1
image:
  repository: 'ghcr.io/tenequm/gelato-technical-challenge'
  tag: '1bdddccc71b93e92dc730dfa41fd8fe0d744949e-6-1'
  pullPolicy: IfNotPresent

# Application port
servicePort: 8080

environments:
  NODE_ENV: 'development'
  ENVIRONMENT: 'local'
  BLOCKCHAIN_NETWORK_NAME: 'goerli'
  RPC_ENDPOINT: 'http://localhost:8080'
  DB_HOST: 'localhost'
  DB_USER: 'local-user'
  DB_PASSWORD: 'local-password'
