name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  init:
    name: Initialise global variables
    runs-on: ubuntu-latest
    outputs:
      GLOBAL_VERSION: ${{ steps.set_ver.outputs.GLOBAL_VERSION }}
    steps:
      - name: Set global version
        id: set_ver
        run: echo "::set-output name=GLOBAL_VERSION::${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

  build:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: app
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.init.outputs.GLOBAL_VERSION }}
